### ISSUE TITLE
print_fee() won't show the total fee correctly

### ISSUE THREAD

**Issue by ChagataiDuru** [ChagataiDuru/CS320-Term-Project-ProCafeOnline#8]
<img width="246" alt="Screenshot 2024-01-02 at 19 36 37" src="https://github.com/ChagataiDuru/CS320-Term-Project-ProCafeOnline/assets/28505248/53cbf4e6-13b9-4810-b8b5-23aa104a57de">

The print_fee() on the main_page_controller.py need fix that total fee not printed correctly

**Comment by umutspring** [comment]
fixed and pushed.
